name: Build container image

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/kurrawong/gsq-prez-ui
  VITE_ENABLED_PREZS: SpacePrez,VocPrez
  VITE_API_BASE_URL: http://localhost:8000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Docker meta
        uses: zazuko/action-docker-meta@main
        id: docker_meta
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VITE_ENABLED_PREZS=${{ env.VITE_ENABLED_PREZS }}
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
          context: .
          file: nginx.Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
