name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

env:
  VITE_ENABLED_PREZS: SpacePrez,VocPrez
  VITE_API_BASE_URL: http://localhost:8000

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clone prez-ui
        run: |
          mkdir ./prez-ui && \
          cd ./prez-ui && \
          git init && \
          git remote add origin https://github.com/RDFLib/prez-ui.git && \
          git fetch --depth 1 origin $(cat ../COMMIT_HASH) && \
          git checkout FETCH_HEAD

      - name: Install Node dependencies
        working-directory: ./prez-ui
        run: npm ci

      - name: Copy QLD Gov Department of Resources theme
        run: |
          mv ./prez-ui/src/App.vue ./prez-ui/src/PrezApp.vue
          cp App.vue ./prez-ui/src/App.vue
          cp public/* ./prez-ui/public/

      - name: Build website
        working-directory: ./prez-ui
        run: npm run build-only -- --base=/qld-resources-prez-ui/

      - name: Add index.html as GH Pages 404 page
        run: cp ./prez-ui/dist/index.html ./prez-ui/dist/404.html

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ./prez-ui/dist
